package action

import (
	"fmt"
	"strings"

	"github.com/SugiKent/loop-cli/internal/model"
)

// markerPlaceholder は行の途中に残った routine マーカーの置き換え先。
// 行ごと落とすと質問文が消えたまま回答行だけが残り、白紙より悪い「完成して見える下書き」になる。
const markerPlaceholder = "[routine マーカー]"

// AnswerTemplate は人への問いの routine コメントから下書きを作る。
// 中身は引用ブロックと回答行を空行 1 行で挟んだもので、投稿すると
// GitHub 上で「引用された問い → 回答」の順に読める。
// 人への問いと読めるコメントが 1 件も無ければ空文字列を返す。
func AnswerTemplate(comments []model.Comment) string {
	body, ok := latestQuestionBody(comments)
	if !ok {
		return ""
	}

	var lines []string
	for _, q := range model.ParseQuestions(body) {
		lines = append(lines, fmt.Sprintf("Q%d: %s", q.Number, defaultLetter(q)))
	}
	answers := strings.Join(lines, "\n")

	quote := quoteQuestion(body)
	if quote == "" {
		return answers
	}
	if answers == "" {
		return quote
	}
	return quote + "\n\n" + answers
}

// latestQuestionBody は comments を末尾から見て、最初に見つかる「人への問い」の
// routine コメントの本文を返す。人への問いが届く形は、grill の質問コメントと
// issue の blocked-by: human コメントの 2 つ。位置で選ばないので、人の返信・
// `started:` の作業印・`## PR リスク評価` のコメントを飛び越えて問いに届く。
func latestQuestionBody(comments []model.Comment) (string, bool) {
	for i := len(comments) - 1; i >= 0; i-- {
		c := comments[i]
		if !c.AI {
			continue
		}
		if len(model.ParseQuestions(c.Body)) > 0 || len(BlockedByLines(c.Body)) > 0 {
			return c.Body, true
		}
	}
	return "", false
}

// quoteQuestion は本文の「質問が始まった行から終わった行まで」を Markdown の引用にする。
// 範囲の中の説明文・表・`- 依存:` の行は、パースできたかどうかを問わず引用に入る。
func quoteQuestion(body string) string {
	lines := strings.Split(body, "\n")
	start, end, ok := questionRange(lines)
	if !ok {
		return ""
	}

	var out []string
	for _, raw := range lines[start : end+1] {
		if isDroppedLine(raw) {
			continue
		}
		line := strings.TrimRight(replaceMarkers(raw), " \t\r")
		if line == "" {
			out = append(out, ">")
			continue
		}
		out = append(out, "> "+line)
	}
	// 範囲の最終行が落とす行だったときに残る `>` を落とし、引用ブロックと回答行の間の空行を 1 行に保つ。
	for len(out) > 0 && out[len(out)-1] == ">" {
		out = out[:len(out)-1]
	}
	return strings.Join(out, "\n")
}

// questionRange は引用する範囲の最初と最後の行の位置を返す。
func questionRange(lines []string) (int, int, bool) {
	end := len(lines) - 1
	for end >= 0 && isTrailingDecoration(lines[end]) {
		end--
	}
	// 見出しの書式は model 側の定義を正本にする。1 行だけ渡すと、見出しの行なら質問が 1 件返る。
	for i := 0; i <= end; i++ {
		if len(model.ParseQuestions(lines[i])) > 0 {
			return i, end, true
		}
	}
	// 見出しが無いコメント（issue の blocked-by: human）は、マーカー行と正本の宣言行を飛ばした後の最初の非空行から。
	for i := 0; i <= end; i++ {
		if strings.TrimSpace(lines[i]) == "" || isDroppedLine(lines[i]) {
			continue
		}
		return i, end, true
	}
	return 0, 0, false
}

// isDroppedLine は引用に入れない行かを返す。マーカーだけの行と、dispatcher の正本の宣言行
// （`blocked-by:` / `unblock-when:`）を持ち回らない（human-turn-signals.md 不変条件 8）。
func isDroppedLine(line string) bool {
	t := strings.TrimSpace(line)
	return t == routineMarker || t == routineMarkerEscaped ||
		strings.HasPrefix(t, blockedByPrefix) || strings.HasPrefix(t, unblockWhenPrefix)
}

// isTrailingDecoration は本文の末尾から落とす行かを返す。空行・区切り線・
// routine の署名（`_Generated by [Claude Code](…)_`）がこれに当たる。
func isTrailingDecoration(line string) bool {
	t := strings.TrimSpace(line)
	if t == "" {
		return true
	}
	// 区切り線は `-` `*` `_` のいずれかが 3 つ以上並んだだけの行。
	if c := t[0]; len(t) >= 3 && strings.ContainsRune("-*_", rune(c)) && strings.Trim(t, string(c)) == "" {
		return true
	}
	return len(t) >= 2 && strings.HasPrefix(t, "_") && strings.HasSuffix(t, "_")
}

// replaceMarkers は行の途中のマーカーを置き換える。判定に使う文字列は
// HasRoutineMarker が見ているものと同じで、テンプレート側で定義し直さない。
func replaceMarkers(line string) string {
	line = strings.ReplaceAll(line, routineMarker, markerPlaceholder)
	return strings.ReplaceAll(line, routineMarkerEscaped, markerPlaceholder)
}

// defaultLetter は質問の既定の選択肢の記号を返す。
func defaultLetter(q model.Question) string {
	for _, o := range q.Options {
		if o.Recommended {
			return o.Letter
		}
	}
	if len(q.Options) > 0 {
		return q.Options[0].Letter
	}
	return ""
}
