package action

import (
	"context"
	"slices"
	"strings"
	"testing"

	"github.com/SugiKent/loop-cli/internal/gh"
	"github.com/SugiKent/loop-cli/internal/model"
)

// aiComment / humanComment は AI 判定を本文に依存させずに列を組み立てる。
func aiComment(body string) model.Comment    { return model.Comment{Body: body, AI: true} }
func humanComment(body string) model.Comment { return model.Comment{Body: body, AI: false} }

// exampleIssueComments は example fixture の issue-108 のコメント列。
func exampleIssueComments(t *testing.T) []model.Comment {
	t.Helper()
	detail, err := newExampleFake().ViewIssue(context.Background(), "org/app", 108)
	if err != nil {
		t.Fatalf("ViewIssue: %v", err)
	}
	return commentsFrom(detail.Comments)
}

// examplePRComments は example fixture の PR のコメント列。
func examplePRComments(t *testing.T, number int) []model.Comment {
	t.Helper()
	detail, err := newExampleFake().ViewPR(context.Background(), "org/app", number)
	if err != nil {
		t.Fatalf("ViewPR: %v", err)
	}
	return commentsFrom(detail.Comments)
}

func commentsFrom(cs []gh.Comment) []model.Comment {
	out := make([]model.Comment, len(cs))
	for i, c := range cs {
		out[i] = model.CommentFrom(c)
	}
	return out
}

// upstreamQuestionBody は routine が実際に PR へ投稿する質問コメントの形。
const upstreamQuestionBody = "<!-- routine -->\n" +
	"未確定の判断が 2 件あります。\n" +
	"\n---\n\n" +
	"### Q1. 状態語の色を端末の背景に追随させるか\n" +
	"\n" +
	"**何の話か**: 説明の段落。\n" +
	"\n" +
	"- **選択肢 A（推奨）**: 2 組を切り替える\n" +
	"- **選択肢 B**: 背景色を敷く\n" +
	"- 依存: なし\n" +
	"\n---\n\n" +
	"### Q2. 色を付ける範囲\n" +
	"\n" +
	"- **選択肢 A**: ラベル名だけ\n" +
	"- **選択肢 B（推奨）**: 状態語まで\n" +
	"\n---\n" +
	"_Generated by [Claude Code](https://claude.ai/code)_"

// TestAnswerTemplateQuotesUpstreamQuestion は実物の質問コメントから引用と回答行ができることを見る。
// 引用は最初の質問見出しから始まり、前置きと署名は入らない。行ごとの包含で見るのは、
// 区切りの 1 行を間違えたときに何が欠けたのかを読めるようにするため。
func TestAnswerTemplateQuotesUpstreamQuestion(t *testing.T) {
	got := AnswerTemplate([]model.Comment{aiComment(upstreamQuestionBody)})
	lines := strings.Split(got, "\n")

	if lines[0] != "> ### Q1. 状態語の色を端末の背景に追随させるか" {
		t.Errorf("1 行目 = %q, want 最初の質問見出しの引用", lines[0])
	}
	for _, want := range []string{
		"> **何の話か**: 説明の段落。",
		"> - **選択肢 A（推奨）**: 2 組を切り替える",
		"> - 依存: なし",
		"> ---",
		"> ### Q2. 色を付ける範囲",
	} {
		if !slices.Contains(lines, want) {
			t.Errorf("引用に %q が無い:\n%s", want, got)
		}
	}
	for _, ng := range []string{"未確定の判断が 2 件あります。", "_Generated by"} {
		if strings.Contains(got, ng) {
			t.Errorf("引用に %q が入っている:\n%s", ng, got)
		}
	}
	if n := len(lines); n < 3 || lines[n-2] != "Q1: A" || lines[n-1] != "Q2: B" || lines[n-3] != "" {
		t.Errorf("末尾 = %q, want 空行 1 行のあとに Q1: A と Q2: B", lines[max(n-3, 0):])
	}
}

func TestAnswerTemplate(t *testing.T) {
	twoQuestions := "<!-- routine -->\n" +
		"以下 2 点、回答をお願いします\n" +
		"## Q1. 名前での絞り込みを今回のスコープに含めるか\n" +
		"- 選択肢 A（推奨）: 含めない。次の issue に回す\n" +
		"- 選択肢 B: 含める\n" +
		"## Q2. カードの情報量の見直しをどこまで行うか\n" +
		"- 選択肢 A: 今回は触らない\n" +
		"- 選択肢 B（推奨）: 幅だけ直す"

	for name, tc := range map[string]struct {
		comments []model.Comment
		want     string
	}{
		"推奨の選択肢が既定値になり、前置きとマーカーは引用に入らない": {
			comments: []model.Comment{aiComment(twoQuestions)},
			want: "> ## Q1. 名前での絞り込みを今回のスコープに含めるか\n" +
				"> - 選択肢 A（推奨）: 含めない。次の issue に回す\n" +
				"> - 選択肢 B: 含める\n" +
				"> ## Q2. カードの情報量の見直しをどこまで行うか\n" +
				"> - 選択肢 A: 今回は触らない\n" +
				"> - 選択肢 B（推奨）: 幅だけ直す\n" +
				"\nQ1: A\nQ2: B",
		},
		"作業印のコメントを飛び越えて問いを選ぶ": {
			comments: []model.Comment{
				aiComment("<!-- routine -->\n### Q1. 分けるか\n- **選択肢 A（推奨）**: 分ける"),
				aiComment("<!-- routine -->\nstarted: 2026-09-11T17:05:00Z\nsession: session_01ABC"),
			},
			want: "> ### Q1. 分けるか\n> - **選択肢 A（推奨）**: 分ける\n\nQ1: A",
		},
		"blocked-by のコメントは引用だけになる": {
			comments: []model.Comment{aiComment("<!-- routine -->\nblocked-by: human\nunblock-when: comment\n\n" +
				"認可の方針をどこに書きますか。docs/policy.md を新しく作るか、README に足すかを決めてください。")},
			want: "> 認可の方針をどこに書きますか。docs/policy.md を新しく作るか、README に足すかを決めてください。",
		},
		// 範囲の中にある正本の宣言行を引用に持ち込まない（不変条件 8）。落としたあとに `>` の行も残さない。
		"範囲の中の blocked-by: と unblock-when: は落ちる": {
			comments: []model.Comment{aiComment("<!-- routine -->\n## Q1. 方式をどうするか\n" +
				"- 選択肢 A（推奨）: 案 1\n\nblocked-by: human\nunblock-when: comment")},
			want: "> ## Q1. 方式をどうするか\n> - 選択肢 A（推奨）: 案 1\n\nQ1: A",
		},
		"末尾の区切り線と署名は引用に入らない": {
			comments: []model.Comment{aiComment("<!-- routine -->\n## Q1. 方式をどうするか\n" +
				"- 選択肢 A（推奨）: 案 1\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n")},
			want: "> ## Q1. 方式をどうするか\n> - 選択肢 A（推奨）: 案 1\n\nQ1: A",
		},
		"エスケープ済みのマーカーの行も落ちる": {
			comments: []model.Comment{aiComment("&lt;!-- routine --&gt;\n## Q1. 方式をどうするか\n- 選択肢 A（推奨）: 案 1")},
			want:     "> ## Q1. 方式をどうするか\n> - 選択肢 A（推奨）: 案 1\n\nQ1: A",
		},
		"見出しの無い質問コメントからは作れない": {
			comments: []model.Comment{aiComment("<!-- routine -->\nQ1: マイグレーションを分けますか。")},
			want:     "",
		},
		"作業印のコメントだけなら空": {
			comments: []model.Comment{aiComment("<!-- routine -->\nstarted: 2026-09-11T17:05:00Z\nsession: session_01ABC")},
			want:     "",
		},
		"リスク評価のコメントだけなら空": {
			comments: []model.Comment{aiComment("## PR リスク評価\n\n影響範囲は小さい。")},
			want:     "",
		},
		"コメントが無い": {comments: nil, want: ""},
		"人のコメントだけ": {
			comments: []model.Comment{humanComment("## Q1. 人が書いた見出し\n- 選択肢 A（推奨）: x")},
			want:     "",
		},
	} {
		t.Run(name, func(t *testing.T) {
			if got := AnswerTemplate(tc.comments); got != tc.want {
				t.Errorf("AnswerTemplate = %q, want %q", got, tc.want)
			}
		})
	}
}

// TestAnswerTemplateDefaultLetter は既定値の選び方（推奨 → 先頭 → 空）を回答行で見る。
func TestAnswerTemplateDefaultLetter(t *testing.T) {
	got := AnswerTemplate([]model.Comment{aiComment(
		"## Q1. 方式をどうするか\n- 選択肢 A: 案 1\n- 選択肢 B: 案 2\n## Q2. 期限はいつか")})
	lines := strings.Split(got, "\n")
	if n := len(lines); n < 2 || lines[n-2] != "Q1: A" || lines[n-1] != "Q2: " {
		t.Errorf("回答行 = %q, want Q1: A と Q2: ", got)
	}
}

// TestAnswerTemplateFixtureWithoutHeading は example の PR 131（`#` の見出しも blocked-by: 行も無い）で
// 空のテンプレートになることを見る。
func TestAnswerTemplateFixtureWithoutHeading(t *testing.T) {
	if got := AnswerTemplate(examplePRComments(t, 131)); got != "" {
		t.Errorf("AnswerTemplate = %q, want 空", got)
	}
}

// TestAnswerTemplateUsesLatestQuestionComment は人への問いを末尾から探すことを検証する。
// 後ろに人のコメントがあっても routine の問いを採り、それより古いコメントは使わない。
func TestAnswerTemplateUsesLatestQuestionComment(t *testing.T) {
	comments := append(exampleIssueComments(t),
		aiComment("## Q1. 方式をどうするか\n- 選択肢 B（推奨）: 案 2"),
		humanComment("## Q1. 人が書いた見出し\n- 選択肢 A（推奨）: x"),
	)
	want := "> ## Q1. 方式をどうするか\n> - 選択肢 B（推奨）: 案 2\n\nQ1: B"
	if got := AnswerTemplate(comments); got != want {
		t.Errorf("AnswerTemplate = %q, want %q", got, want)
	}
}

// TestAnswerTemplateReplacesInlineMarker は行の途中のマーカーを置き換えて残すことを見る。
// 行ごと落とすと質問文が消えたまま回答行だけが残り、投稿もできなくなる。
func TestAnswerTemplateReplacesInlineMarker(t *testing.T) {
	got := AnswerTemplate([]model.Comment{aiComment(
		"<!-- routine -->\n## Q1. 先頭に <!-- routine --> を入れるか\n- 選択肢 A（推奨）: 入れない")})

	if !strings.Contains(got, "> ## Q1. 先頭に [routine マーカー] を入れるか") {
		t.Errorf("AnswerTemplate = %q, want 置き換えた質問行を含む", got)
	}
	if !strings.HasSuffix(got, "\nQ1: A") {
		t.Errorf("AnswerTemplate = %q, want Q1: A で終わる", got)
	}
	if HasRoutineMarker(got) {
		t.Errorf("AnswerTemplate = %q, want マーカーを含まない（含むと投稿できない）", got)
	}

	escaped := AnswerTemplate([]model.Comment{aiComment(
		"&lt;!-- routine --&gt;\n## Q1. 方式をどうするか\n- 選択肢 A（推奨）: 案 1")})
	if HasRoutineMarker(escaped) {
		t.Errorf("AnswerTemplate = %q, want エスケープ済みのマーカーも含まない", escaped)
	}
}
